package com.comtrades.app;
import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.view.animation.*;import android.widget.*;import android.content.*;import android.content.res.ColorStateList;
public class MainActivity extends Activity{
 int bg=Color.rgb(7,10,12),glass=Color.rgb(22,28,31),muted=Color.rgb(150,160,168),green=Color.rgb(83,226,147),amber=Color.rgb(255,190,72); LinearLayout root,content;String project="Northpoint Offices";
 int dp(float x){return(int)(x*getResources().getDisplayMetrics().density+.5f);} TextView tx(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setIncludeFontPadding(false);return v;}void bold(TextView v){v.setTypeface(null,Typeface.BOLD);}void pad(View v,int a,int b,int c,int d){v.setPadding(dp(a),dp(b),dp(c),dp(d));}
 GradientDrawable shape(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));g.setStroke(dp(1),Color.argb(45,220,255,242));return g;}
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(bg);getWindow().setNavigationBarColor(bg);getWindow().getDecorView().setSystemUiVisibility(0);home();}
 void base(String title,boolean back){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);int top=24; if(Build.VERSION.SDK_INT>=23)top=36;pad(root,20,top,20,12);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);if(back){TextView b=tx("‹",38,Color.WHITE);b.setGravity(Gravity.CENTER);b.setOnClickListener(v->home());bar.addView(b,new LinearLayout.LayoutParams(dp(38),dp(54)));}TextView h=tx(title,back?25:32,Color.WHITE);bold(h);h.setMaxLines(2);h.setEllipsize(android.text.TextUtils.TruncateAt.END);bar.addView(h,new LinearLayout.LayoutParams(0,-2,1));root.addView(bar);ScrollView sv=new ScrollView(this);sv.setClipToPadding(false);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);pad(content,0,14,0,36);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);enter(root);}
 void label(String s){TextView v=tx(s,12,green);v.setLetterSpacing(.1f);content.addView(v);}void title(String s){TextView v=tx(s,38,Color.WHITE);bold(v);content.addView(v);}void space(int n){content.addView(new Space(this),new LinearLayout.LayoutParams(1,dp(n)));}
 void home(){base("ComTrades",false);label("FIELD OPERATIONS");title("Projects");content.addView(tx("3 active jobs  ·  71% overall complete",15,muted));space(20);job("Riverside Medical Center",78);job("Union Station Retrofit",61);job("Northpoint Offices",74);}
 void job(String n,int pct){LinearLayout c=glassCard();TextView h=tx(n,21,Color.WHITE);bold(h);h.setMaxLines(2);c.addView(h);c.addView(tx("Washington, DC  •  ACTIVE",13,muted));Space s=new Space(this);c.addView(s,new LinearLayout.LayoutParams(1,dp(16)));ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setMax(100);p.setProgress(pct);p.setProgressTintList(ColorStateList.valueOf(green));c.addView(p,new LinearLayout.LayoutParams(-1,dp(5)));c.addView(tx(pct+"% complete",14,Color.LTGRAY));press(c,()->{project=n;overview();});content.addView(c);space(12);}
 LinearLayout glassCard(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);pad(c,18,18,18,18);c.setBackground(shape(glass,22));c.setElevation(dp(5));return c;}
 void overview(){base(project,true);((ViewGroup)root.getChildAt(0)).getChildAt(0).setOnClickListener(v->home());label("PROJECT COMMAND CENTER");title("Overview");space(14);LinearLayout hero=glassCard();TextView k=tx("61% COMPLETE",12,green);hero.addView(k);TextView n=tx("311 / 506",34,Color.WHITE);bold(n);hero.addView(n);hero.addView(tx("devices installed and verified",14,muted));content.addView(hero);space(14);action("draw","DRAWINGS","Live plans & mapped devices",()->drawings());action("scan","SCAN DRAWING","Import a plan & detect field scope",()->scan());action("work","MY WORK","38 assigned  •  26 complete",()->drawings());action("issue","ISSUES","6 open issues need attention",()->issues());}
 void action(String icon,String a,String b,Runnable r){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);pad(row,14,13,14,13);row.setBackground(shape(Color.rgb(18,24,27),24));row.setElevation(dp(6));GlassIconView iv=new GlassIconView(this,icon);row.addView(iv,new LinearLayout.LayoutParams(dp(64),dp(64)));LinearLayout words=new LinearLayout(this);words.setOrientation(LinearLayout.VERTICAL);pad(words,13,0,0,0);TextView h=tx(a,18,Color.WHITE);bold(h);h.setMaxLines(2);words.addView(h);TextView sub=tx(b,13,muted);sub.setMaxLines(2);words.addView(sub);row.addView(words,new LinearLayout.LayoutParams(0,-2,1));TextView arrow=tx("›",30,Color.rgb(190,205,200));row.addView(arrow);press(row,r);content.addView(row,new LinearLayout.LayoutParams(-1,dp(94)));space(11);}
 void drawings(){base("Drawings",true);((ViewGroup)root.getChildAt(0)).getChildAt(0).setOnClickListener(v->overview());label(project.toUpperCase());title("Live plans");content.addView(tx("Original construction drawings with the ComTrades field layer on top.",14,muted));space(16);plan("Level 01 — Life Safety",72);plan("Level 02 — Electrical",69);plan("Level 03 — Security",67);action("scan","IMPORT & SCAN","Analyze another construction PDF",()->scan());}
 void plan(String n,int pct){LinearLayout c=glassCard();MiniPlan p=new MiniPlan(this);c.addView(p,new LinearLayout.LayoutParams(-1,dp(165)));Space s=new Space(this);c.addView(s,new LinearLayout.LayoutParams(1,dp(12)));TextView h=tx(n,19,Color.WHITE);bold(h);h.setMaxLines(2);c.addView(h);c.addView(tx(pct+"% complete  •  mapped devices",13,muted));press(c,()->viewer(n));content.addView(c);space(12);}
 void scan(){base("Scan Drawing",true);((ViewGroup)root.getChildAt(0)).getChildAt(0).setOnClickListener(v->overview());label("COMTRADES VISION");title("Import & detect");content.addView(tx("Use the contractor's real PDF. ComTrades learns the sheet legend, finds field devices and traces cable scope.",15,muted));space(20);LinearLayout up=glassCard();GlassIconView i=new GlassIconView(this,"scan");LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(dp(88),dp(88));ip.gravity=Gravity.CENTER;up.addView(i,ip);TextView h=tx("Choose construction PDF",20,Color.WHITE);bold(h);h.setGravity(Gravity.CENTER);up.addView(h);TextView s=tx("PDF  •  issued plans  •  revisions",13,muted);s.setGravity(Gravity.CENTER);up.addView(s);press(up,()->scanRun());content.addView(up);space(20);pipeline("draw","READ DRAWING","Sheet geometry, rooms, notes & legend");pipeline("scan","DETECT DEVICES","Cameras, readers, fire alarm, data & more");pipeline("cable","TRACE CABLE","Runs, cable labels, endpoints & pathways");pipeline("work","REVIEW CONFIDENCE","Flag uncertain findings before publishing");}
 void pipeline(String icon,String a,String b){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);GlassIconView i=new GlassIconView(this,icon);r.addView(i,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout w=new LinearLayout(this);w.setOrientation(LinearLayout.VERTICAL);pad(w,12,0,0,0);TextView h=tx(a,14,Color.WHITE);bold(h);w.addView(h);w.addView(tx(b,12,muted));r.addView(w,new LinearLayout.LayoutParams(0,-2,1));content.addView(r);space(14);}
 void scanRun(){base("Analyzing",true);label("LIVE SCAN");title("E2.01.pdf");ScanPlan p=new ScanPlan(this);content.addView(p,new LinearLayout.LayoutParams(-1,dp(290)));space(18);TextView st=tx("Reading drawing…",16,Color.WHITE);bold(st);content.addView(st);ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(100);bar.setProgressTintList(ColorStateList.valueOf(green));content.addView(bar,new LinearLayout.LayoutParams(-1,dp(7)));String[] a={"Reading drawing…","Learning legend…","Detecting devices…","Tracing cable…","Checking confidence…","347 devices found"};Handler hh=new Handler(Looper.getMainLooper());for(int x=0;x<a.length;x++){final int q=x;hh.postDelayed(()->{st.setText(a[q]);bar.setProgress((q+1)*100/a.length);p.phase=q+1;p.invalidate();if(q==a.length-1)hh.postDelayed(()->results(),650);},500+q*650);}}
 void results(){base("Scan Results",true);label("SCAN COMPLETE");title("347 devices");content.addView(tx("301 high confidence  •  38 review  •  8 duplicates",14,muted));space(16);metric("Cameras","38","94%");metric("Card readers","17","91%");metric("Data drops","44","88%");metric("Door / REX","38","84%");metric("CAT6 / CAT6A","8,420 ft","86%");space(12);action("work","REVIEW 38 FINDINGS","Confirm uncertain detections",()->results());action("draw","PUBLISH TO FIELD","Create the live device map",()->drawings());}
 void metric(String a,String b,String c){LinearLayout r=glassCard();LinearLayout line=new LinearLayout(this);TextView l=tx(a+"\n"+c+" confidence",15,Color.WHITE);line.addView(l,new LinearLayout.LayoutParams(0,-2,1));TextView v=tx(b,18,green);bold(v);v.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);line.addView(v);r.addView(line);content.addView(r);space(8);}
 void issues(){base("Issues",true);label("FIELD ISSUES");title("6 open");action("issue","DRAWING CONFLICT","Level 02  •  CAM-214",()->{});action("cable","CABLE PATH BLOCKED","Level 02  •  CAM-219",()->{});}
 void viewer(String name){base(name,true);label("LIVE DEVICE MAP");content.addView(tx("127 / 184 complete  •  69%",14,green));space(10);Map m=new Map(this);content.addView(m,new LinearLayout.LayoutParams(-1,dp(570)));}
 void press(View v,Runnable r){v.setOnTouchListener((x,e)->{if(e.getAction()==0)x.animate().scaleX(.97f).scaleY(.97f).alpha(.86f).setDuration(80).start();else if(e.getAction()==1){x.animate().scaleX(1).scaleY(1).alpha(1).setDuration(220).setInterpolator(new OvershootInterpolator(.7f)).withEndAction(r).start();}else if(e.getAction()==3)x.animate().scaleX(1).scaleY(1).alpha(1).setDuration(120).start();return true;});}void enter(View v){v.setAlpha(0);v.setTranslationY(dp(16));v.animate().alpha(1).translationY(0).setDuration(330).setInterpolator(new DecelerateInterpolator()).start();}
 class MiniPlan extends View{Paint p=new Paint(3);MiniPlan(Context c){super(c);setBackground(shape(Color.rgb(226,225,217),16));}protected void onDraw(Canvas c){float w=getWidth(),h=getHeight();p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(1));p.setColor(Color.DKGRAY);c.drawRect(w*.06f,h*.1f,w*.94f,h*.9f,p);for(float x:new float[]{.28f,.52f,.76f})c.drawLine(w*x,h*.1f,w*x,h*.9f,p);for(float y:new float[]{.35f,.67f})c.drawLine(w*.06f,h*y,w*.94f,h*y,p);p.setStyle(Paint.Style.FILL);for(int i=0;i<10;i++){p.setColor(i%3==0?amber:green);c.drawCircle(w*(.12f+(i%5)*.18f),h*(.25f+(i/5)*.45f),dp(5),p);}}}
 class ScanPlan extends MiniPlan{int phase=0;Paint q=new Paint(3);ScanPlan(Context c){super(c);}protected void onDraw(Canvas c){super.onDraw(c);float y=getHeight()*(.12f+.12f*phase);q.setColor(Color.argb(180,83,226,147));q.setStrokeWidth(dp(3));q.setShadowLayer(dp(10),0,0,green);c.drawLine(0,y,getWidth(),y,q);q.clearShadowLayer();}}
 class Map extends MiniPlan{Map(Context c){super(c);}protected void onDraw(Canvas c){super.onDraw(c);Paint q=new Paint(3);q.setTextAlign(Paint.Align.CENTER);q.setTextSize(dp(9));for(int i=0;i<9;i++){float x=getWidth()*(.14f+(i%3)*.3f),y=getHeight()*(.2f+(i/3)*.28f);q.setColor(i%3==0?amber:green);q.setShadowLayer(dp(8),0,0,q.getColor());c.drawCircle(x,y,dp(14),q);q.clearShadowLayer();q.setColor(Color.rgb(10,15,15));c.drawText("CAM",x,y+dp(3),q);}}}
}
