package com.comtrades.app;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.view.animation.*;import android.widget.*;import android.content.*;import android.content.res.ColorStateList;import java.util.*;

public class MainActivity extends Activity{
 int bg=Color.rgb(9,11,13),card=Color.rgb(23,27,30),card2=Color.rgb(31,36,39),muted=Color.rgb(148,156,164),green=Color.rgb(83,226,147),amber=Color.rgb(255,190,72),red=Color.rgb(255,99,99); LinearLayout root,content; String currentProject="Union Station Retrofit";
 int dp(float n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} TextView t(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setIncludeFontPadding(false);return v;} GradientDrawable box(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;} void bold(TextView v){v.setTypeface(null,Typeface.BOLD);} void pad(View v,int a,int b,int c,int d){v.setPadding(dp(a),dp(b),dp(c),dp(d));}
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(bg);getWindow().setNavigationBarColor(bg);home();}
 void base(String title,boolean back){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);pad(root,20,18,20,10);root.setBackgroundColor(bg);TextView h=t((back?"‹  ":"")+title,back?24:30,Color.WHITE);bold(h);h.setGravity(Gravity.CENTER_VERTICAL);h.setSingleLine(false);if(back)h.setOnClickListener(v->home());root.addView(h,new LinearLayout.LayoutParams(-1,-2));spaceRoot(18);ScrollView s=new ScrollView(this);s.setClipToPadding(false);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);s.addView(content);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);fade(root);}
 void home(){base("ComTrades",false);label("FIELD OPERATIONS");heading("Projects");content.addView(t("3 active jobs  ·  71% overall complete",16,muted));space(22);project("Riverside Medical Center","Washington, DC","642 / 824 devices",78);project("Union Station Retrofit","Washington, DC","311 / 506 devices",61);project("Northpoint Offices","Arlington, VA","188 / 253 devices",74);space(14);}
 void label(String s){TextView v=t(s,12,green);v.setLetterSpacing(.08f);content.addView(v);} void heading(String s){TextView h=t(s,36,Color.WHITE);bold(h);content.addView(h);}
 void project(String n,String loc,String count,int pct){LinearLayout c=card();TextView x=t(n,22,Color.WHITE);bold(x);x.setMaxLines(2);c.addView(x);c.addView(t(loc+"  •  ACTIVE JOB",13,muted));spaceIn(c,16);ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setMax(100);p.setProgressTintList(ColorStateList.valueOf(green));c.addView(p,new LinearLayout.LayoutParams(-1,dp(6)));animateProgress(p,pct);spaceIn(c,12);c.addView(t(count+"     "+pct+"% complete",15,Color.LTGRAY));press(c,()->{currentProject=n;projectScreen(n);});content.addView(c,new LinearLayout.LayoutParams(-1,-2));space(14);}
 LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);pad(c,19,19,19,19);c.setBackground(box(card,20));return c;}
 void projectScreen(String n){base(n,true);root.getChildAt(0).setOnClickListener(v->home());label("PROJECT COMMAND CENTER");heading("Overview");space(8);LinearLayout hero=card();hero.addView(t("61% COMPLETE",12,green));TextView big=t("311 / 506",32,Color.WHITE);bold(big);hero.addView(big);hero.addView(t("devices installed and verified",14,muted));spaceIn(hero,14);ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setMax(100);p.setProgressTintList(ColorStateList.valueOf(green));hero.addView(p,new LinearLayout.LayoutParams(-1,dp(7)));animateProgress(p,61);content.addView(hero);space(14);action("▣  DRAWINGS","Open live plans and device maps",()->drawings(n));action("✦  SCAN DRAWING","Import a plan and auto-detect field scope",()->scanHub());action("⚡  MY WORK","38 assigned  •  26 complete",()->drawings(n));action("!  ISSUES","6 open issues need attention",()->issues());}
 void action(String a,String b,Runnable r){LinearLayout c=card();TextView h=t(a,18,Color.WHITE);bold(h);c.addView(h);spaceIn(c,6);c.addView(t(b,14,muted));press(c,r);content.addView(c);space(11);}
 void drawings(String project){base(project,true);root.getChildAt(0).setOnClickListener(v->projectScreen(project));label("LIVE DRAWINGS");heading("Plans");content.addView(t("Original construction plans with ComTrades field overlays.",14,muted));space(18);drawing("Level 01 — Life Safety","128 devices  •  72% complete");drawing("Level 02 — Electrical","184 devices  •  69% complete");drawing("Level 03 — Security","156 devices  •  67% complete");space(10);action("＋  IMPORT & SCAN DRAWING","PDF plans are analyzed automatically",()->scanHub());}
 void drawing(String n,String sub){LinearLayout c=card();Plan v=new Plan(this);c.addView(v,new LinearLayout.LayoutParams(-1,dp(190)));spaceIn(c,13);TextView x=t(n,20,Color.WHITE);bold(x);x.setMaxLines(2);c.addView(x);c.addView(t(sub,13,muted));press(c,()->viewer(n));content.addView(c);space(13);}
 void scanHub(){base("Import & Scan",true);root.getChildAt(0).setOnClickListener(v->projectScreen(currentProject));label("COMTRADES VISION");heading("Scan a drawing");content.addView(t("Import the contractor's actual PDF. ComTrades analyzes the sheet, legend, device symbols, labels and cable scope.",15,muted));space(20);LinearLayout upload=card();TextView icon=t("＋",38,green);bold(icon);icon.setGravity(Gravity.CENTER);upload.addView(icon);TextView a=t("Choose construction PDF",19,Color.WHITE);bold(a);a.setGravity(Gravity.CENTER);upload.addView(a);TextView b=t("PDF • issued drawings • revisions",13,muted);b.setGravity(Gravity.CENTER);upload.addView(b);pad(upload,20,28,20,28);press(upload,()->runScan());content.addView(upload);space(20);label("AUTO-DETECTION PIPELINE");pipeline("01","Read sheet + drawing legend","Learns what symbols mean on this plan");pipeline("02","Detect field devices","Cameras, readers, data, fire alarm, speakers and more");pipeline("03","Trace cable scope","Cable labels, runs, endpoints and pathways");pipeline("04","Review confidence","Low-confidence findings are flagged before publishing");}
 void pipeline(String no,String a,String b){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.TOP);TextView num=t(no,13,green);bold(num);row.addView(num,new LinearLayout.LayoutParams(dp(42),dp(40)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);TextView h=t(a,16,Color.WHITE);bold(h);tx.addView(h);tx.addView(t(b,13,muted));row.addView(tx,new LinearLayout.LayoutParams(0,-2,1));content.addView(row);space(16);}
 void runScan(){base("Scanning drawing",true);root.getChildAt(0).setOnClickListener(v->scanHub());label("ANALYZING IMPORT");heading("E2.01.pdf");content.addView(t("Finding devices, reading labels and tracing field scope…",15,muted));space(24);ScanView sv=new ScanView(this);content.addView(sv,new LinearLayout.LayoutParams(-1,dp(260)));space(20);TextView status=t("Preparing drawing…",16,Color.WHITE);bold(status);content.addView(status);ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setMax(100);p.setProgressTintList(ColorStateList.valueOf(green));content.addView(p,new LinearLayout.LayoutParams(-1,dp(8)));String[]steps={"Reading sheet geometry…","Learning legend symbols…","Detecting cameras and field devices…","Tracing cable runs…","Scoring confidence…","Scan complete"};Handler h=new Handler(Looper.getMainLooper());for(int i=0;i<steps.length;i++){final int q=i;h.postDelayed(()->{status.setText(steps[q]);p.setProgress((q+1)*100/steps.length);sv.phase=q+1;sv.invalidate();if(q==steps.length-1)h.postDelayed(()->scanResults(),650);},500+i*650);}}
 void scanResults(){base("Scan Results",true);root.getChildAt(0).setOnClickListener(v->scanHub());label("SCAN COMPLETE");heading("347 devices found");content.addView(t("E2.01.pdf  •  Level 02",14,muted));space(18);stats("301","HIGH CONFIDENCE",green);stats("38","NEED REVIEW",amber);stats("8","POSSIBLE DUPLICATES",red);space(18);label("DETECTED SCOPE");scope("Cameras","38","94%");scope("Card readers","17","91%");scope("Data drops","44","88%");scope("Door contacts / REX","38","84%");scope("Other field devices","210","93%");space(16);label("CABLE SCOPE");scope("CAT6 / CAT6A","8,420 ft","86%");scope("18/2","3,180 ft","78%");scope("22/4","2,760 ft","81%");space(18);action("REVIEW 38 FINDINGS →","Confirm uncertain symbols before publishing",()->review());action("PUBLISH TO FIELD","Create the interactive live device map",()->drawings(currentProject));}
 void stats(String n,String s,int c){LinearLayout x=card();TextView a=t(n,30,c);bold(a);x.addView(a);x.addView(t(s,12,muted));content.addView(x);space(9);} void scope(String a,String b,String conf){LinearLayout r=new LinearLayout(this);TextView l=t(a+"\n"+conf+" confidence",15,Color.WHITE);r.addView(l,new LinearLayout.LayoutParams(0,dp(52),1));TextView rr=t(b,17,green);bold(rr);rr.setGravity(Gravity.RIGHT);r.addView(rr,new LinearLayout.LayoutParams(dp(110),dp(52)));content.addView(r);}
 void review(){base("Review Findings",true);root.getChildAt(0).setOnClickListener(v->scanResults());label("HUMAN REVIEW");heading("38 need review");content.addView(t("Tap the correct classification. Corrections improve this project's symbol understanding.",14,muted));space(18);for(int i=0;i<6;i++)finding(i);}
 void finding(int i){LinearLayout c=card();Plan p=new Plan(this);c.addView(p,new LinearLayout.LayoutParams(-1,dp(115)));spaceIn(c,10);TextView h=t("Possible "+(i%2==0?"CAMERA":"DATA DROP")+"  •  "+(62+i*4)+"%",17,amber);bold(h);c.addView(h);c.addView(t("Sheet E2.01  •  Grid "+(char)('B'+i)+"4",13,muted));spaceIn(c,10);LinearLayout buttons=new LinearLayout(this);String[]bs={"CAMERA","DATA","OTHER","DELETE"};for(String s:bs){Button b=new Button(this);b.setText(s);b.setTextSize(11);buttons.addView(b,new LinearLayout.LayoutParams(0,dp(44),1));}c.addView(buttons);content.addView(c);space(12);}
 void issues(){base("Issues",true);root.getChildAt(0).setOnClickListener(v->projectScreen(currentProject));label("FIELD ISSUES");heading("6 open");for(int i=0;i<4;i++)action("!  "+(i%2==0?"Drawing conflict":"Cable path blocked"),"Level 02 • FA-2"+(14+i)+" • assigned",()->{});}
 void viewer(String n){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);pad(root,16,14,16,12);root.setBackgroundColor(bg);TextView h=t("‹  "+n,20,Color.WHITE);bold(h);h.setMaxLines(2);h.setOnClickListener(v->drawings(currentProject));root.addView(h);spaceRoot(8);root.addView(t("127 / 184 complete  •  69%",13,green));spaceRoot(10);MapView m=new MapView(this);root.addView(m,new LinearLayout.LayoutParams(-1,0,1));TextView hint=t("Pinch/drag map prototype  •  Tap device for field status",12,muted);hint.setGravity(Gravity.CENTER);root.addView(hint,new LinearLayout.LayoutParams(-1,dp(46)));setContentView(root);fade(root);}
 void device(int i,MapView m){final Dialog d=new Dialog(this);LinearLayout sh=card();pad(sh,22,22,22,22);TextView id=t("CAM-"+(210+i),25,Color.WHITE);bold(id);sh.addView(id);sh.addView(t(m.done[i]?"✓ COMPLETE":"○ NOT STARTED",14,m.done[i]?green:amber));spaceIn(sh,14);sh.addView(t("IP CAMERA\nLevel 02 • Corridor C • Grid 4B\nCable: CAT6A • IDF-2A → Device",15,Color.LTGRAY));spaceIn(sh,18);Button b=new Button(this);b.setText(m.done[i]?"MARK NOT STARTED":"MARK COMPLETE ✓");b.setOnClickListener(v->{m.done[i]=!m.done[i];m.invalidate();d.dismiss();});sh.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));d.setContentView(sh);Window w=d.getWindow();if(w!=null){w.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));w.setLayout(-1,-2);w.setGravity(Gravity.BOTTOM);}d.show();if(d.getWindow()!=null){d.getWindow().setLayout(-1,-2);d.getWindow().setGravity(Gravity.BOTTOM);} }
 void press(View v,Runnable r){v.setOnTouchListener((x,e)->{if(e.getAction()==MotionEvent.ACTION_DOWN)x.animate().scaleX(.975f).scaleY(.975f).setDuration(90).start();if(e.getAction()==MotionEvent.ACTION_UP){x.animate().scaleX(1).scaleY(1).setDuration(130).withEndAction(r).start();}if(e.getAction()==MotionEvent.ACTION_CANCEL)x.animate().scaleX(1).scaleY(1).setDuration(100).start();return true;});} void fade(View v){v.setAlpha(0);v.setTranslationY(dp(12));v.animate().alpha(1).translationY(0).setDuration(280).setInterpolator(new DecelerateInterpolator()).start();} void animateProgress(ProgressBar p,int end){p.setProgress(0);new Handler(Looper.getMainLooper()).postDelayed(()->{android.animation.ObjectAnimator.ofInt(p,"progress",0,end).setDuration(700);android.animation.ObjectAnimator a=android.animation.ObjectAnimator.ofInt(p,"progress",0,end);a.setDuration(700);a.start();},180);}
 void space(int n){content.addView(new Space(this),new LinearLayout.LayoutParams(1,dp(n)));}void spaceIn(LinearLayout l,int n){l.addView(new Space(this),new LinearLayout.LayoutParams(1,dp(n)));}void spaceRoot(int n){root.addView(new Space(this),new LinearLayout.LayoutParams(1,dp(n)));}
 class Plan extends View{Paint p=new Paint(1);Plan(Context c){super(c);setBackground(box(Color.rgb(232,230,221),14));}protected void onDraw(Canvas c){float w=getWidth(),h=getHeight();p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(1));p.setColor(Color.rgb(65,67,66));c.drawRect(w*.06f,h*.1f,w*.94f,h*.9f,p);for(float x:new float[]{.22f,.43f,.68f,.82f})c.drawLine(w*x,h*.1f,w*x,h*.9f,p);for(float y:new float[]{.28f,.51f,.72f})c.drawLine(w*.06f,h*y,w*.94f,h*y,p);p.setStyle(Paint.Style.FILL);for(int i=0;i<12;i++){p.setColor(i%4==0?amber:green);float x=w*(.11f+(i%6)*.145f),y=h*(.2f+(i/6)*.47f);c.drawCircle(x,y,dp(5),p);}}}
 class ScanView extends Plan{int phase=0;Paint q=new Paint(1);ScanView(Context c){super(c);}protected void onDraw(Canvas c){super.onDraw(c);float y=getHeight()*(.12f+(.75f*((phase%6)/6f)));q.setColor(Color.argb(120,83,226,147));q.setStrokeWidth(dp(3));c.drawLine(0,y,getWidth(),y,q);q.setStyle(Paint.Style.STROKE);q.setStrokeWidth(dp(2));q.setColor(green);for(int i=0;i<phase*2;i++){float x=getWidth()*(.13f+(i%5)*.17f),yy=getHeight()*(.22f+(i%3)*.24f);c.drawCircle(x,yy,dp(13),q);}q.setStyle(Paint.Style.FILL);}}
 class MapView extends View{Paint p=new Paint(1);boolean[]done={true,true,false,true,false,true,true,false,true,true,false,true};float[]xs={.14f,.28f,.42f,.62f,.79f,.2f,.51f,.72f,.87f,.35f,.57f,.68f},ys={.2f,.3f,.18f,.27f,.17f,.58f,.51f,.62f,.48f,.78f,.82f,.73f};float ox,oy,lx,ly;MapView(Context c){super(c);setBackground(box(Color.rgb(235,233,224),18));}protected void onDraw(Canvas c){float w=getWidth(),h=getHeight();c.save();c.translate(ox,oy);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(1));p.setColor(Color.DKGRAY);c.drawRect(w*.05f,h*.06f,w*.95f,h*.94f,p);for(float x:new float[]{.2f,.39f,.61f,.8f})c.drawLine(w*x,h*.06f,w*x,h*.94f,p);for(float y:new float[]{.27f,.49f,.7f})c.drawLine(w*.05f,h*y,w*.95f,h*y,p);p.setStyle(Paint.Style.FILL);for(int i=0;i<xs.length;i++){p.setColor(done[i]?green:amber);c.drawCircle(w*xs[i],h*ys[i],dp(12),p);p.setColor(Color.rgb(15,20,20));p.setTextAlign(Paint.Align.CENTER);p.setTextSize(dp(8));c.drawText("CAM",w*xs[i],h*ys[i]+dp(3),p);}c.restore();}public boolean onTouchEvent(MotionEvent e){if(e.getAction()==0){lx=e.getX();ly=e.getY();return true;}if(e.getAction()==2){ox+=e.getX()-lx;oy+=e.getY()-ly;lx=e.getX();ly=e.getY();invalidate();return true;}if(e.getAction()==1){float w=getWidth(),h=getHeight(),best=99999;int bi=-1;for(int i=0;i<xs.length;i++){float d=(float)Math.hypot(e.getX()-ox-w*xs[i],e.getY()-oy-h*ys[i]);if(d<best){best=d;bi=i;}}if(best<dp(38))device(bi,this);return true;}return true;}}
}
