package com.comtrades.app;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import android.content.*;import java.util.*;

public class MainActivity extends Activity {
 int bg=Color.rgb(11,13,15),card=Color.rgb(25,29,32),muted=Color.rgb(145,153,160),green=Color.rgb(87,226,148),yellow=Color.rgb(255,196,84); LinearLayout root,content;
 int dp(float n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} TextView t(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);return v;} GradientDrawable box(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(bg);home();}
 void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(20),dp(14),dp(20),dp(10));root.setBackgroundColor(bg);TextView h=t(title,28,Color.WHITE);h.setTypeface(null,1);root.addView(h,new LinearLayout.LayoutParams(-1,dp(52)));ScrollView s=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);s.addView(content);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 void home(){base("ComTrades");content.addView(t("FIELD OPERATIONS",12,green));TextView h=t("Projects",34,Color.WHITE);h.setTypeface(null,1);content.addView(h);content.addView(t("3 active jobs  ·  71% overall complete",15,muted));space(20);project("Riverside Medical Center","Washington, DC","642 / 824 devices",78);project("Union Station Retrofit","Washington, DC","311 / 506 devices",61);project("Northpoint Offices","Arlington, VA","188 / 253 devices",74);}
 void project(String n,String loc,String count,int pct){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(17),dp(18),dp(17));c.setBackground(box(card,18));TextView x=t(n,21,Color.WHITE);x.setTypeface(null,1);c.addView(x);c.addView(t(loc+"  •  ACTIVE JOB",12,muted));spaceIn(c,14);ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setMax(100);p.setProgress(pct);p.setProgressTintList(android.content.res.ColorStateList.valueOf(green));c.addView(p,new LinearLayout.LayoutParams(-1,dp(5)));spaceIn(c,10);c.addView(t(count+"     "+pct+"% complete",14,Color.LTGRAY));c.setOnClickListener(v->drawings(n));content.addView(c,new LinearLayout.LayoutParams(-1,dp(150)));space(12);}
 void drawings(String project){base("‹  "+project);root.getChildAt(0).setOnClickListener(v->home());content.addView(t("DRAWINGS",12,green));TextView h=t("Plans",32,Color.WHITE);h.setTypeface(null,1);content.addView(h);content.addView(t("Tap a plan to open the live device map.",14,muted));space(18);drawing("Level 01 — Life Safety","128 devices  •  72% complete");drawing("Level 02 — Electrical","184 devices  •  69% complete");drawing("Level 03 — Fire Alarm","156 devices  •  67% complete");}
 void drawing(String n,String sub){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(16),dp(16),dp(14));c.setBackground(box(card,18));Plan v=new Plan(this);c.addView(v,new LinearLayout.LayoutParams(-1,dp(150)));spaceIn(c,10);TextView x=t(n,19,Color.WHITE);x.setTypeface(null,1);c.addView(x);c.addView(t(sub,13,muted));c.setOnClickListener(vw->viewer(n));content.addView(c,new LinearLayout.LayoutParams(-1,dp(220)));space(12);}
 void viewer(String n){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(10),dp(16),dp(12));root.setBackgroundColor(bg);TextView h=t("‹  "+n,20,Color.WHITE);h.setTypeface(null,1);h.setGravity(Gravity.CENTER_VERTICAL);h.setOnClickListener(v->drawings("Riverside Medical Center"));root.addView(h,new LinearLayout.LayoutParams(-1,dp(56)));root.addView(t("127 / 184 complete  •  69%",13,green));spaceRoot(10);MapView m=new MapView(this);root.addView(m,new LinearLayout.LayoutParams(-1,0,1));TextView hint=t("Drag to explore  •  Tap a device to change status",12,muted);hint.setGravity(Gravity.CENTER);root.addView(hint,new LinearLayout.LayoutParams(-1,dp(42)));setContentView(root);}
 void device(int i,MapView m){AlertDialog.Builder b=new AlertDialog.Builder(this);b.setTitle("Device FA-2."+(110+i));b.setMessage((m.done[i]?"✓ COMPLETE":"○ NOT STARTED")+"\n\nLevel 02 · Corridor C · Grid 4B\nFire Alarm Device");b.setPositiveButton(m.done[i]?"MARK NOT STARTED":"MARK COMPLETE",(d,w)->{m.done[i]=!m.done[i];m.invalidate();});b.setNegativeButton("CLOSE",null);b.show();}
 void space(int n){content.addView(new Space(this),new LinearLayout.LayoutParams(1,dp(n)));}void spaceIn(LinearLayout l,int n){l.addView(new Space(this),new LinearLayout.LayoutParams(1,dp(n)));}void spaceRoot(int n){root.addView(new Space(this),new LinearLayout.LayoutParams(1,dp(n)));}
 class Plan extends View{Paint p=new Paint(1);Plan(Context c){super(c);setBackground(box(Color.rgb(235,233,225),12));}protected void onDraw(Canvas c){float w=getWidth(),h=getHeight();p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(1));p.setColor(Color.DKGRAY);c.drawRect(w*.08f,h*.12f,w*.92f,h*.86f,p);for(float x:new float[]{.35f,.65f})c.drawLine(w*x,h*.12f,w*x,h*.86f,p);c.drawLine(w*.08f,h*.5f,w*.92f,h*.5f,p);p.setStyle(Paint.Style.FILL);p.setColor(green);for(int i=0;i<7;i++)c.drawCircle(w*(.15f+i*.11f),h*(.28f+(i%2)*.4f),dp(5),p);}}
 class MapView extends View{Paint p=new Paint(1);boolean[]done={true,true,false,true,false,true,true,false,true,true,false,true};float[]xs={.14f,.28f,.42f,.62f,.79f,.2f,.51f,.72f,.87f,.35f,.57f,.68f},ys={.2f,.3f,.18f,.27f,.17f,.58f,.51f,.62f,.48f,.78f,.82f,.73f};float ox,oy,lx,ly;MapView(Context c){super(c);setBackground(box(Color.rgb(236,234,226),18));}protected void onDraw(Canvas c){float w=getWidth(),h=getHeight();c.save();c.translate(ox,oy);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(1.2f));p.setColor(Color.DKGRAY);c.drawRect(w*.06f,h*.08f,w*.94f,h*.92f,p);for(float x:new float[]{.25f,.48f,.7f})c.drawLine(w*x,h*.08f,w*x,h*.92f,p);for(float y:new float[]{.32f,.55f,.76f})c.drawLine(w*.06f,h*y,w*.94f,h*y,p);p.setStyle(Paint.Style.FILL);for(int i=0;i<xs.length;i++){p.setColor(done[i]?green:yellow);c.drawCircle(w*xs[i],h*ys[i],dp(12),p);p.setColor(Color.rgb(20,25,25));p.setTextAlign(Paint.Align.CENTER);p.setTextSize(dp(10));c.drawText(done[i]?"✓":"•",w*xs[i],h*ys[i]+dp(4),p);}p.setTextAlign(Paint.Align.LEFT);c.restore();}public boolean onTouchEvent(android.view.MotionEvent e){if(e.getAction()==0){lx=e.getX();ly=e.getY();return true;}if(e.getAction()==2){ox+=e.getX()-lx;oy+=e.getY()-ly;lx=e.getX();ly=e.getY();invalidate();return true;}if(e.getAction()==1){float w=getWidth(),h=getHeight(),best=99999;int bi=-1;for(int i=0;i<xs.length;i++){float d=(float)Math.hypot(e.getX()-ox-w*xs[i],e.getY()-oy-h*ys[i]);if(d<best){best=d;bi=i;}}if(best<dp(35))device(bi,this);return true;}return true;}}
}
